server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/spotify_api?useSSL=false
    dbname: spotify_api
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

